### ISSUE TITLE
Fast traversal per type

### ISSUE THREAD

**Issue by renau** [masc-ucsc/livehd#122]
**What?**
Group all the same type per page (128 entries). Then, when traversing a given type (Subgraph), we can have
a very efficient/fast traversal.

**Why?**
There are lots of passes that check type.
We could also have a more efficient branch prediction if consecutive traversals return same type

**Comment by rafaeltp** [comment]
Doesn't that increase the number of long edges?

**Comment by renau** [comment]
Good point. It would increase, but I noticed that for many passes we do load and then branch in op. If we cluster the bpred and looking for type should go way faster.

Not a high priority change, but I would not mind to explore this (I should benchmark more firesim with long/short now that we have larger designs)

**Comment by rafaeltp** [comment]
I think it makes sense to benchmark.
another point to consider is mapped netlists, where most nodes have the same type.

But I agree that it makes sense as an optimization.
