### ISSUE TITLE
Request for pyrope language reference mannual, and programing tutorials

### ISSUE THREAD

**Issue by kevinyuan** [masc-ucsc/livehd#182]
I am aware of a slide deck talking about pyrope advantage vs other languages, along with some code examples.

However, I haven't found any formal pyrope language reference manual for designers to start programming.

Beside that, a series of programing tutorials would also be very helpful.

Thanks.

Kevin.

**Comment by renau** [comment]
You are right that those things are needed. For the moment, the language is still not open because we are finishing it and testing it internally. We hope to have a release early 2021. (with some manuals)
