### ISSUE TITLE
File and class naming conventions

### ISSUE THREAD

**Issue by rafaeltp** [masc-ucsc/livehd#56]
Some files added to pass/dfg don't follow the naming convention for lgraph.

- File names should me lower case only, words split by underscore.
- Class names should have first letter upper case and words split by underscore, no camel case.

Also, are we using a different convention for C++ in Pyrope?
Since some of those are in the namespace Pyrope, it could make sense to use the Pyrope convention, but maybe we should have a single convention for both projects.

**Comment by hskinner** [comment]
There was a different naming convention for Pyrope, but I think there should be one for both projects.
